load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_library")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

kt_jvm_library(
    name = "functions_framework_invoker_process",
    srcs = ["FunctionsFrameworkInvokerProcess.kt"],
    deps = [
        "//imports/java/org/jetbrains/annotations",
        "//imports/kotlin/kotlinx/coroutines:core",
        "//src/main/kotlin/org/wfanet/measurement/common",
    ],
)
