load("@rules_jvm_external//:defs.bzl", "maven_export")
load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_library")
load("//build/maven:defs.bzl", "artifact_version")

package(
    default_testonly = True,
    default_visibility = ["//visibility:public"],
)

MAVEN_COORDINATES = "org.wfanet.measurement:common-testing:" + artifact_version()

kt_jvm_library(
    name = "functions_framework_invoker_process",
    srcs = ["FunctionsFrameworkInvokerProcess.kt"],
    tags = ["maven_coordinates=" + MAVEN_COORDINATES],
    deps = [
        "//imports/java/org/jetbrains/annotations",
        "//imports/kotlin/kotlinx/coroutines:core",
        "//src/main/kotlin/org/wfanet/measurement/common",
    ],
)

maven_export(
    name = "common_testing_maven",
    testonly = True,
    lib_name = "functions_framework_invoker_process",
    maven_coordinates = MAVEN_COORDINATES,
    tags = ["no-javadocs"],
    visibility = ["//visibility:private"],
)
