load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_test")

kt_jvm_test(
    name = "ConfidentialSpaceTokenClientTest",
    srcs = ["ConfidentialSpaceTokenClientTest.kt"],
    test_class = "org.wfanet.measurement.gcloud.confidentialspace.ConfidentialSpaceTokenClientTest",
    runtime_deps = ["//imports/java/io/netty:transport_native_epoll"],
    deps = [
        "//imports/java/com/google/common/truth",
        "//imports/java/io/netty:buffer",
        "//imports/java/io/netty:codec_http",
        "//imports/java/io/netty:transport",
        "//imports/java/io/netty:transport_classes_epoll",
        "//imports/java/io/netty:transport_native_unix_common",
        "//imports/java/org/junit",
        "//imports/kotlin/kotlin/test",
        "//src/main/kotlin/org/wfanet/measurement/gcloud/confidentialspace:confidential_space_token_client",
    ],
)
