load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_test")

sh_binary(
    name = "function_process_test_server",
    srcs = ["FunctionProcessTestServer.sh"],
)

kt_jvm_test(
    name = "FunctionsFrameworkInvokerProcessTest",
    srcs = ["FunctionsFrameworkInvokerProcessTest.kt"],
    data = [":function_process_test_server"],
    test_class = "org.wfanet.measurement.gcloud.testing.FunctionsFrameworkInvokerProcessTest",
    deps = [
        "//imports/java/com/google/common/truth",
        "//imports/java/org/junit",
        "//imports/kotlin/kotlin/test",
        "//imports/kotlin/kotlinx/coroutines:core",
        "//src/main/kotlin/org/wfanet/measurement/gcloud/testing:functions_framework_invoker_process",
    ],
)
