load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_library")

package(default_visibility = ["//visibility:public"])

kt_jvm_library(
    name = "confidential_space_token_client",
    srcs = ["ConfidentialSpaceTokenClient.kt"],
    deps = [
        "//imports/java/com/google/gson",
        "//imports/java/io/netty/channel/unix",
        "//imports/java/io/netty/handler/codec:http",
        "//imports/java/reactor:core",
        "//imports/java/reactor/netty:core",
        "//imports/java/reactor/netty/http",
    ],
)
